version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./src:/app/src:delegate
      - ./static:/app/static:delegate
    ports:
      - "8000:8000"
